config/routes.rb
Rails.application.routes.draw do
  # resources :books, only: [:new, :create, :show]
  resources :books

  resources :authors
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories, only: [:new, :create, :show]
  root "books#index"

  scope :books do
    resources :comments, only: [:new, :create, :destroy]
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books
  has_many :comments, :through => :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :authors
  has_many :comment, dependent: :destroy

  has_attached_file :image, styles: { medium: "600x600>", thumb: "150x150>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, presence: true,
            uniqueness: { case_sensitive: false }
  validates :image, presence: true
  validates :description, presence: true
  validates :authors, presence: true
  validates :categories, presence: true



end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  RAIT = (1..5).to_a

  validates :rating, presence: true, numericality: true
  validates :comment, presence: true, length: { minimum: 3 }
  validates_numericality_of :rating, :greater_than => 0, :message => "должен быть больше чем 0"
  validates_numericality_of :rating, :less_than => 6, :message => "должен быть меньше чем 6"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books, dependent: :destroy
  has_many :comment, dependent: :destroy

  def active_for_authentication?
    #remember to call the super
    #then put our own check to determine "active" state using
    #our own "is_active" column
    super and self.is_active?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < InheritedResources::Base

  private

    def author_params
      params.require(:author).permit(:name, :status)
    end
end

app/controllers/books_controller.rb
class BooksController < InheritedResources::Base

  before_action :authenticate_user!, only: [:new, :create]


  def index
    @books = if params[:term]

               Book.where('name LIKE ?', "%#{params[:term]}%")
             else
               Book.where(status: true)
             end
  end

  def create

    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = "Книга добавлена! Она будет отображена после модерации"
      redirect_to books_path
    else
      render 'new'
    end
  end



  private

    def book_params
      params.require(:book).permit(:name, :image, :description, :term, category_ids: [], author_ids: [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    category = Category.find(params[:id])
    @books = category.books.where(status: true)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

        # узнаем, оставлял ли юзер коммент к этой книге ранее

    old_comment = Comment.where(book_id: @comment.book_id, user_id: current_user.id).count


    if old_comment != 0
      flash[:success] = "Сперва нужно удалить старый комментарий"
      redirect_to "/books/#{@comment.book_id}"

    else
      if @comment.save
        flash[:success] = "Комментарий добавлен"
        redirect_to "/books/#{@comment.book_id}"
      else
        flash[:error] = "Правильно заполните поля"
        redirect_to "/books/#{@comment.book_id}"
      end

    end


  end

  def destroy

    @comment = Comment.find(params[:id])
    if @comment.user_id == current_user.id

    @comment = Comment.destroy(params[:id])
    respond_to do |format|
      format.js {
        flash[:success] = "Комментарий удален"
        redirect_to "/books/#{@comment.book_id}"
      }
      format.html {

      }
    end

    else
      flash[:error] = "Нельзя удалить чужой отзыв"
      redirect_to "/books/#{@comment.book_id}"
    end

  end


  private

  def comment_params
    params.require(:comment).permit(:rating, :comment, :book_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :author_name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, id: :author_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.status %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @author.status %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :book_name %>

    <%= form.label :image %>
    <%= form.file_field :image, id: :book_image %>

    <%= form.label :description %>
    <%= form.text_area :description, id: :description_name %>

    <%= form.label "Жанр" %><br />
    <%= form.collection_select :category_ids, Category.all, :id, :name, {}, { multiple: true } %>

    <%= form.label "Автор" %><br />
    <%= form.collection_select :author_ids, Author.all, :id, :name, {}, { multiple: true } %>


    <p>
      <input type="checkbox" id="terms">
      <label for="terms">I have read the terms of use</label>
    </p>
  </div>



  <div class="actions">
    <%= form.submit id: "send" %>
  </div>
<% end %>

<script>
  $(function () {
      var button = $('#send');
      button.attr('disabled', 'disabled');
      $('#terms').change(function (e) {
          if (this.checked) {
              button.removeAttr('disabled');
          } else
              button.att('disabled','disabled');

      })
  })
</script>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<%= form_tag(books_path, method: :get) do %>
    <%= text_field_tag :term, params[:term], placeholder: "Ищите книгу? напечатайте, например 'new one'" %><br>
<br>
    <%= submit_tag 'Search', name: nil %>
<% end %>


<div class="container">
  <div class="box">
    <% @books.each do |book| %>
        <div>
          <%= link_to book.name, "/books/#{book.id}" %><br>

          <%= image_tag book.image.url(:thumb) %> <br>



          <% book.categories.each do |cat| %>

              <%= link_to cat.name, "/categories/#{cat.id}" %> <br>
          <% end %>
          Отзывов: <%= book.comment.count %><br>





          <div class="review-rating" data-score=" <%= book.comment.average(:rating).to_i %>"></div>

        </div>
    <% end %>
  </div>
</div>

<script>
    $('.review-rating').raty({
        readOnly: true,
        score: function () {
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Cover:</strong>
  <%= image_tag @book.image.url(:medium) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>


<p>
  <strong>User:</strong>
  <%= @book.user.email %>
</p>

<p>
  <strong>Created:</strong>
  <%= @book.created_at %>
</p>


<p><b>Категория:</b><br>
  <% @book.categories.each do |cat| %>
      <%= cat.name %> <br>
  <% end %>
</p>

<p><b>Автор:</b><br>
  <% @book.authors.each do |author| %>
      <%= author.name %><br>
  <% end %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>



<div class="row">
  <div class="span6 offset3">
    <%= form_for(:comment, url: comments_path) do |f| %>

        <div id="rating-form">
          <label> Rating </label>
        </div>

        <%= f.label :comment %>
        <%= f.text_area :comment %>

        <%= f.hidden_field :book_id, :value => @book.id %>

        <%= f.submit "Добавить комментарий", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>
</div>

<% @book.comment.each do |comment| %>
    <div id="comment-<%=comment.id%>">
      <li>
        <p>
        <div class="review-rating" data-score="<%= comment.rating %>"></div>

        </p>
        <p>
          <i><%= comment.user.email %> said(<%= comment.created_at %>):</i> <%= comment.comment %>
        </p>

         <% if comment.user_id == current_user.id %>
        <%= link_to "Удалить", comment, method: :delete, class: "btn btn-primary", remote: true %>
            <% end %>

      </li>
    </div>
<% end %>


<script>
  $('.review-rating').raty({
      readOnly: true,
      score: function () {
          return $(this).attr('data-score');
      },
      path: '/assets/'
  });
</script>

<script>
    $('#rating-form').raty({
        path: '/assets',
        scoreName: 'comment[rating]'
    });
</script>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<div class="container">
  <div class="box">
    <% @books.each do |book| %>
        <div>
          <%= link_to book.name, "/books/#{book.id}" %><br>

          <%= image_tag book.image.url(:thumb) %> <br>



          <% book.categories.each do |cat| %>

              <%= link_to cat.name, "/categories/#{cat.id}" %> <br>
          <% end %>
          Отзывов: <%= book.comment.count %><br>





          <div class="review-rating" data-score=" <%= book.comment.average(:rating).to_i %>"></div>

        </div>
    <% end %>
  </div>
</div>

<script>
    $('.review-rating').raty({
        readOnly: true,
        score: function () {
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

app/views/comments/_show_error.html.erb
<% if @comment.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@comment.errors.count, "error") %>.
      </div>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/comments/error_message.js.erb
$("#comments").append("<%= j render 'show_error' %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FINAL</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Library</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% if user_signed_in? %>
          <li> <%= link_to current_user.email, edit_user_registration_path(current_user)%> </li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            <li><%= link_to "Create book", new_book_path %></li>
        <% else %>
            <li><%= link_to "Sing up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>